# Codecov configuration for FDA Tools
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%           # overall project coverage target
        threshold: 2%         # allow 2% drop before failing
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 70%           # new code in PRs must be ≥70% covered
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "plugins/fda_tools/tests/**"
  - "scripts/**"
  - "**/__pycache__/**"
