/**
 * FDA-251  [FE-013] AI Inline Suggestions Panel
 * ===============================================
 * Sidebar panel that presents AI-generated suggestions for the current
 * document section.  Each suggestion card has:
 *   - Original text excerpt (strikethrough)
 *   - Proposed replacement text
 *   - Accept / Reject buttons
 *   - Confidence score + rationale
 *
 * Architecture
 * ------------
 * - Accepts a list of `AiSuggestion` objects (generated by the backend)
 * - Calls `onAccept(suggestion)` / `onReject(id)` callbacks
 * - Parent (DocumentStudio page) is responsible for applying the accepted
 *   text to the TipTap editor via `editor.commands.insertContentAt()`
 * - Pending suggestions have a pulsing amber accent
 * - No direct API calls; driven entirely by props
 */

"use client";

import { useState } from "react";
import {
  CheckCircle2, XCircle, ChevronDown, ChevronUp,
  Sparkles, AlertCircle, Info,
} from "lucide-react";
import { Badge }  from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

// ── Types ─────────────────────────────────────────────────────────────────────

export type SuggestionStatus = "pending" | "accepted" | "rejected";

export interface AiSuggestion {
  id:           string;
  sectionType:  string;
  /** Original text that should be replaced (empty = insertion at end) */
  originalText: string;
  /** Proposed replacement / insertion */
  proposedText: string;
  /** Human-readable rationale for the suggestion */
  rationale:    string;
  /** 0.0–1.0 confidence */
  confidence:   number;
  /** Category tag: "clarity" | "completeness" | "compliance" | "formatting" */
  category:     "clarity" | "completeness" | "compliance" | "formatting";
  status:       SuggestionStatus;
}

// ── Category colours ──────────────────────────────────────────────────────────

const CAT_CLASSES: Record<AiSuggestion["category"], string> = {
  clarity:      "bg-blue-50 text-blue-700 border-blue-200",
  completeness: "bg-purple-50 text-purple-700 border-purple-200",
  compliance:   "bg-red-50 text-red-700 border-red-200",
  formatting:   "bg-gray-50 text-gray-700 border-gray-200",
};

const CAT_ICONS: Record<AiSuggestion["category"], typeof Info> = {
  clarity:      Info,
  completeness: AlertCircle,
  compliance:   AlertCircle,
  formatting:   Info,
};

// ── Demo suggestions (shown when list is empty / loading) ─────────────────────

export const DEMO_SUGGESTIONS: AiSuggestion[] = [
  {
    id:           "s1",
    sectionType:  "intended-use",
    originalText: "The device is used for cardiac procedures.",
    proposedText:
      "The device is indicated for single-use diagnostic catheterization of the coronary and peripheral vasculature in adult patients.",
    rationale:
      "FDA reviewers expect a specific indication statement. The original text lacks patient population, anatomical site, and single-use designation.",
    confidence:   0.91,
    category:     "compliance",
    status:       "pending",
  },
  {
    id:           "s2",
    sectionType:  "intended-use",
    originalText: "",
    proposedText:
      "This device is not intended for use in pediatric patients under 18 years of age.",
    rationale:
      "Adding a contraindication for pediatric use is standard for adult-indicated cardiovascular devices and reduces RTA risk.",
    confidence:   0.78,
    category:     "completeness",
    status:       "pending",
  },
  {
    id:           "s3",
    sectionType:  "intended-use",
    originalText: "single use",
    proposedText: "single-use (not intended for reprocessing or reuse)",
    rationale:
      "FDA guidance recommends explicit reuse prohibition language aligned with ISO 11135 labeling requirements.",
    confidence:   0.85,
    category:     "clarity",
    status:       "pending",
  },
];

// ── Individual suggestion card ────────────────────────────────────────────────

function SuggestionCard({
  suggestion,
  onAccept,
  onReject,
}: {
  suggestion: AiSuggestion;
  onAccept:   (s: AiSuggestion) => void;
  onReject:   (id: string)      => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const CatIcon = CAT_ICONS[suggestion.category];
  const isPending  = suggestion.status === "pending";
  const isAccepted = suggestion.status === "accepted";

  return (
    <div
      className={[
        "rounded-lg border transition-all",
        isPending  ? "border-amber-200 bg-amber-50/40 dark:border-amber-800 dark:bg-amber-950/20" : "",
        isAccepted ? "border-green-200 bg-green-50/30 opacity-70" : "",
        !isPending && !isAccepted ? "border-muted bg-muted/20 opacity-50" : "",
      ].join(" ")}
    >
      {/* Card header */}
      <div className="flex items-start gap-2 p-3">
        <Sparkles
          className={`mt-0.5 h-4 w-4 shrink-0 ${isPending ? "text-amber-500" : "text-muted-foreground"}`}
        />
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <Badge className={`text-[10px] ${CAT_CLASSES[suggestion.category]}`}>
              <CatIcon className="mr-0.5 h-2.5 w-2.5" />
              {suggestion.category}
            </Badge>
            <span className="text-[11px] text-muted-foreground">
              {Math.round(suggestion.confidence * 100)}% confidence
            </span>
            {suggestion.status !== "pending" && (
              <Badge variant={isAccepted ? "default" : "secondary"} className="text-[10px]">
                {suggestion.status}
              </Badge>
            )}
          </div>

          {/* Proposed text preview */}
          <p className="mt-1.5 text-sm leading-snug">
            {expanded
              ? suggestion.proposedText
              : suggestion.proposedText.slice(0, 80) + (suggestion.proposedText.length > 80 ? "…" : "")}
          </p>

          {/* Original text (struck) */}
          {suggestion.originalText && (
            <p className="mt-1 text-xs text-muted-foreground line-through">
              {suggestion.originalText.slice(0, 60)}{suggestion.originalText.length > 60 ? "…" : ""}
            </p>
          )}

          {/* Rationale (collapsible) */}
          {expanded && (
            <p className="mt-2 rounded bg-muted/50 px-2 py-1.5 text-xs text-muted-foreground">
              {suggestion.rationale}
            </p>
          )}
        </div>

        {/* Expand toggle */}
        <button
          onClick={() => setExpanded((e) => !e)}
          className="mt-0.5 rounded p-0.5 text-muted-foreground hover:bg-muted"
        >
          {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
        </button>
      </div>

      {/* Accept / Reject actions */}
      {isPending && (
        <div className="flex gap-2 border-t bg-muted/20 px-3 py-2">
          <Button
            size="sm"
            variant="default"
            className="h-7 flex-1 gap-1 text-xs"
            onClick={() => onAccept(suggestion)}
          >
            <CheckCircle2 className="h-3.5 w-3.5" /> Accept
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 flex-1 gap-1 text-xs text-destructive hover:text-destructive"
            onClick={() => onReject(suggestion.id)}
          >
            <XCircle className="h-3.5 w-3.5" /> Reject
          </Button>
        </div>
      )}
    </div>
  );
}

// ── Main panel ────────────────────────────────────────────────────────────────

export interface AiSuggestionsPanelProps {
  suggestions:  AiSuggestion[];
  isLoading?:   boolean;
  onAccept:     (suggestion: AiSuggestion) => void;
  onReject:     (id: string) => void;
  /** Called to re-generate suggestions for the current section */
  onRefresh?:   () => void;
}

export function AiSuggestionsPanel({
  suggestions,
  isLoading  = false,
  onAccept,
  onReject,
  onRefresh,
}: AiSuggestionsPanelProps) {
  const [filter, setFilter] = useState<"all" | "pending" | "accepted" | "rejected">("pending");

  const visible = suggestions.filter(
    (s) => filter === "all" || s.status === filter,
  );
  const pendingCount  = suggestions.filter((s) => s.status === "pending").length;
  const acceptedCount = suggestions.filter((s) => s.status === "accepted").length;

  return (
    <div className="flex flex-col gap-3">
      {/* Panel header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-amber-500" />
          <span className="text-sm font-semibold">AI Suggestions</span>
          {pendingCount > 0 && (
            <Badge className="bg-amber-100 text-amber-800 text-[10px]">
              {pendingCount} pending
            </Badge>
          )}
        </div>
        {onRefresh && (
          <Button
            variant="ghost"
            size="sm"
            className="h-7 text-xs"
            onClick={onRefresh}
            disabled={isLoading}
          >
            {isLoading ? "Generating…" : "Refresh"}
          </Button>
        )}
      </div>

      {/* Filter tabs */}
      <div className="flex rounded-lg bg-muted/50 p-0.5 text-xs">
        {(["pending", "all", "accepted", "rejected"] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={[
              "flex-1 rounded-md py-1 capitalize transition-colors",
              filter === f ? "bg-background shadow-sm font-medium" : "text-muted-foreground hover:text-foreground",
            ].join(" ")}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Summary stats */}
      <div className="grid grid-cols-3 gap-2 text-center text-xs">
        <div className="rounded border p-1.5">
          <p className="text-base font-bold text-amber-600">{pendingCount}</p>
          <p className="text-muted-foreground">Pending</p>
        </div>
        <div className="rounded border p-1.5">
          <p className="text-base font-bold text-green-600">{acceptedCount}</p>
          <p className="text-muted-foreground">Accepted</p>
        </div>
        <div className="rounded border p-1.5">
          <p className="text-base font-bold text-muted-foreground">
            {suggestions.filter((s) => s.status === "rejected").length}
          </p>
          <p className="text-muted-foreground">Rejected</p>
        </div>
      </div>

      {/* Loading skeleton */}
      {isLoading && (
        <div className="space-y-2">
          {[0, 1, 2].map((i) => (
            <div key={i} className="h-24 animate-pulse rounded-lg bg-muted" />
          ))}
        </div>
      )}

      {/* Suggestion cards */}
      {!isLoading && visible.length === 0 && (
        <div className="flex flex-col items-center gap-2 rounded-lg border-2 border-dashed py-8 text-center">
          <CheckCircle2 className="h-8 w-8 text-muted-foreground/30" />
          <p className="text-sm text-muted-foreground">
            {filter === "pending" ? "No pending suggestions" : `No ${filter} suggestions`}
          </p>
        </div>
      )}

      {!isLoading && visible.map((s) => (
        <SuggestionCard
          key={s.id}
          suggestion={s}
          onAccept={onAccept}
          onReject={onReject}
        />
      ))}
    </div>
  );
}
